version: "3"
services:
  node:
    container_name: shotz_node
    restart: always
    build: ./backend/
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    container_name: shotz_db
    image: mongo
    ports:
      - "27000:27017"
    volumes:
      - "/data/shotz/db:/data/db"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: shotz-password
