version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27000:27017'
    volumes:
      - '/data/shotz/db:/data/db'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: shotz-password
