export default {
    REGISTER: "REGISTER",
    CATEGORY_SELECT: "CATEGORY_SELECT",
    IN_ROUND: "IN_ROUND",
    END_ROUND: "END_ROUND",
    END_GAME: "END_GAME",
    SUBMIT_CLOSED: "SUBMIT_CLOSED"
};
